bf283dd50041bcc4a8524b5d3f2adf1294f98a0a smd: add function smsm_change_state_nonotify 4d4db58bb30a8bf147b6de6dcd4d61846be21d1e Cleanup and prepare for boot f7b3c8b84401fbe5c57961d856c99f6c8f659d66 Add footswitch device before adreno to control gpu power properly 9e47edfff081a1054326ba3fdb7707befb39f936 Add MSM Codec/Cpu Dai driver 3c537dda7e2f3852b83018be2cb2de5f8e5130bd Add footswitch devices & remove auto generated smd_rpc_sym.c 275f72d81a7f37fa4992851f8779ac06f0ed6bc0 Update board files d6fee8104fa439dff4c592e7fdec7176f00a258e regulator: ldo05 range changed d3bba5ca33adba70230e59b25353199e30c8125d msm: Enable handset driver 9ec34fb02bb6d075604a874fbdee1f15fde291dd Merge "Revert "Temporarily revert the Novatek driver"" into cm-10.1 be10896b6d2f3f5416d12c8ef3f011ce8ff8750d Revert "Temporarily revert the Novatek driver" 2b03eeab96caebdae64e6254459f775be69f2529 Merge "Temporarily revert the Novatek driver" into cm-10.1 e5b1b5d190994a8e7991b6e3da88ae2a77767b1c Temporarily revert the Novatek driver 42291b638d0c4c171b47d3ccc71f3bdd6ebaa5aa Merge "p50x: Update configs" into cm-10.1 2f5b66247b616b581eed017bc7f27bb1bccc0196 Merge "Set dload magic number for ram dump when ARM9 crash" into cm-10.1 03982a1f54c9be7f2ea3230b553249591c279cc9 Merge "More modem crash crap" into cm-10.1 b7af14a18d31775ef641f1425c6c886b457939f3 p50x: Update configs 372dffb2e8408f130f41cbb67b0ff1568120221f regulator: ranges changed 6b5faf5d3dc6b6607b638fa02ba603f91f2f87f5 regulator: value correction for wireless driver Signed-off-by: Randolf Kastenmaier <randolf.kastenmaier@gmail.com> 0e4c69d648e5493bf7e0e6669a6ec32e14c93da0 Set dload magic number for ram dump when ARM9 crash d54d7708d744863acb8edbdb1bc89872e32ed4bc More modem crash crap 631d16a106dc8247edc01dca06e60b93c8da2ca6 Merge "Modify auotcheck point of yaffs file system." into cm-10.1 dba4d85226c983ce3b02c43a0dd5c84614de7ef8 Merge "Add ISX006 driver" into cm-10.1 e4e5f630aad513467a3cc845c49715145d49d024 Merge "ISX005 camera driver bringup" into cm-10.1 8c45640533da136d524c8044d2fa411bcdd11dc6 Merge "Fix ktime_t error in Vibrator" into cm-10.1 e75d0c294c7675c7d37f3228b53bc994f3aaa187 Merge "Change function name *pwn* -> *pwm* in Vibrator" into cm-10.1 13021a7761ad0e6ebcf0f7ffeb09978b6dc08406 Merge "Add android vibrator device driver" into cm-10.1 505ad62a092b3df9a4febdfc72b9932044bf529b Fix ktime_t error in Vibrator 00714340d5e67076a02dcd9623cdfc9e28e9bab2 Change function name *pwn* -> *pwm* in Vibrator dc4240d5af29ccd27d7aeb5014e1c827a567d367 Makefile: add -fno-pic to module flags 4b810338c9d410e8a62a7f9c0d0929a252a075b8 Add ISX006 driver e38db468f8e9d0f3217f8570b83d3ea789fdebba ISX005 camera driver bringup bfb1b75a4b4081e0843e5bd72078a9eaf8584deb regulator: value correction for the sensors f4514ef914644bf741b85fe40a5c7e7bbeb44115 Merge "Display crash log" into cm-10.1 00fbd2539952c09cc1cb5c9df54b0bc38865220a Merge "Fix thunderg NAND size Signed-off-by: Rashed Abdel-Tawab <rashedabdeltawab@gmail.com>" into cm-10.1 982c1ff24da0dfb83d88dc0c0c73762e5fcd4d8b Merge "Update MTC and support airplane mode" into cm-10.1 689e360796888af70deddb955c7be641c4c1cb10 Merge "Migrate LG test mode" into cm-10.1 9488ab13b9d85fea0a222ca458c42dbb44d12e81 Merge "Add debug mesg in msm7k_handset & gpio_matrix key" into cm-10.1 ab236316f2b210a16c97b0bb9ab27a4293a847c4 Merge "Add atcommand virtual keyboard driver" into cm-10.1 09cc3c045b439f63b2fd2cb5eaa53d95f54c0f2e Merge "Add splint support" into cm-10.1 2de9a553b9af5f578bce5bf0edd6ac0203cc75b1 Display crash log 369a8c15507c9d3aa420f716d31c13486b925215 LED: Set TUNED brightness to 127 2e15482d6be60b17016f647b3794f7031f7e5c12 LED driver: add shutdown routine 32a13b731d529c39cbfba72f7bf3c2143442137f Initial LG LED bringup fcbc95455687a012d1a658fb44f39f29434762ee Add android vibrator device driver de87d8e92d2cd8f14f627816c20df74bd870807f Merge "regulator: wrong values are set" into cm-10.1 1dc1595582bd621c5d46d57bc03da0b71f076c68 ARM: Force software TLS on ARMv6 Important to complete kernel booting Signed-off-by: Randolf Kastenmaier <randolf.kastenmaier@gmail.com> 143749fd561d655461eb4c468d54cad0ddbee43d Add splint support ff63b9ffdcd544512a1ff050ed27059d7dff330c Update MTC and support airplane mode 58d05b7206b7fa9bdc3df544644c3304c0540f58 Migrate LG test mode 71dd104c50e324dfbccd9841e99d70fab1fa8dc1 Add atcommand virtual keyboard driver 4eb802531da0f5e1f7d07436a3523015dcb9b0e2 Add debug mesg in msm7k_handset & gpio_matrix key 19240aa84ef9eae76eb0c0bc0871c4988dd3d2c6 Fix thunderg NAND size Signed-off-by: Rashed Abdel-Tawab <rashedabdeltawab@gmail.com> 58bd93000228d930fb5ecfa84521f87107644fbc display driver: Moved configurations for hitachi and novatek to the selection list Signed-off-by: Randolf Kastenmaier <randolf.kastenmaier@gmail.com> 5a1b1bd93d402821b14314872649fbf983319215 sensors: missing sensors enabled e7b1415eba4e6a0c3ae8733388a44fd21e095f48 regulator: wrong values are set 7769152dd66d9538f4b6289e857095fb2d1c4fa0 Merge "Fix uart3 clock lookup for 7x27" into cm-10.1 5228e68601e105ed0765cf844e63fded50837699 Updated p50x def config 03f0aef6af590e3cd526e0fc36578c29af4b92d3 Modify auotcheck point of yaffs file system. dde78c8117b2b7ad00932ecaf7149c5859e89338 Fix uart3 clock lookup for 7x27 434456f1a44900978a35d96f8bc2521afde44e37 revert my commit mistake 738eaf19450662e023f3b6dac01c6fc09d9c46eb tweak the build script a bit. 257f1e64960404df42b966a2bf013b1453dfbe8c add in build script f2f61f6851faad1a1c4c6d5654399f05d037008b fix up all p350 errors 127b9d25d9c51c23c5521ad69d56e40c79466c24 update bcm4329 39d8a790a099d79ae2d02ecc133e68cb6f0092cb fix p350 errors 47608a7dbbc42742b6066bb4b249cc1537a5555b config: def configs for p50x updated some modules are important to pass lge logo. So modules (wifi and scsi excluded) are now build into kernel, so we can't forget to include them. Kernel logo is enabled to see the switch from kernel loading to rom boot. f3faea428590492c6e72c0c6f19ff2639d5847cd Enable XZ decompresser for better compression ratio 60615cd8072083159ca754c4eedfa9fe5780919c build ebi2_tovis for CONFIG_FB_MSM_EBI2 6857ca28d19214d069a6e71eccf5eff13f4e75ab ARM: 7001/2: Wire up support for the XZ decompressor e29ae4cf3ef5b268e1507770decd7b5c2207abe9 Merge "Revert "Left Ear-jack detection & End Key enable"" into cm-10.1 e0e1665bf25492e5041d15b5411b2566b29dcb0b Revert "Left Ear-jack detection & End Key enable" 6d4d5db35dd4e80051abe784f4a14bbaf6b27bfb Merge "Left Ear-jack detection & End Key enable" into cm-10.1 b70721bffac00e25d3f8e0e220bcbd59ec345460 Update P50X family defconfigs 9ab55f98b0ec3fc85008984aa354737222debac2 Left Ear-jack detection & End Key enable d63d18f242e6c41e8dc29f49dc5cbae2629ee45b Merge "Modify the base of memory map for CONFIG_VMSPLIT 3G/1G." into cm-10.1 2b2d6218fb937d8e9cba5c05df25145ed9ffc4fd Allow physical start address of the first bank of RAM for each board 202c5e4bad7143f52636e2956734d0b432a5e7e0 boot: Add march=armv6 flag 8cb81438434578bea8357d5dea55517ae9bfd1b5 Fix novatek/hitachi display table 3400f789d47e8c6e6c5f40994f933dc3681d79e6 Revert "Fix Novatek driver build error" ef0adbbaa799167a024f206818c4d6ab0fd82846 Revert "Fix MSM video drivers build errors" 08e9f272b579e8c22c9208e621bd47088b38973e Modify the base of memory map for CONFIG_VMSPLIT 3G/1G. b659ab07cd2f6e0271a473e3b9457c40f6e3ec1d Do not use wrapper for compiler 4b854d2c49a95f1119b56a274fbe19a05a97dd81 Fix MSM video drivers build errors 608396c55fe3fd1f5ae46a614b9216d024daa4ee Update P505/P506 configs... AGAIN 5be30b8288b30ef2b7c32a4c61c50f5115ecfd4c Merge "Fix Novatek driver build error" into cm-10.1 3299ac992d147362da24b62bc7a92fab21caad78 Fix Novatek driver build error c50ab9355d9dfe90bde635b7bcf0f521edaba08f Fix Kconfigs b790d09bfe21427a6c2494694ab72196d2b0b2a0 Update P505/P506 config be830bdc58e8ff459336cccdea6f244bceec2f50 Merge "Remove platform devices for USB functions" into cm-10.1 e423e411f34d197f8b72f119cb494402d321a19e Merge "Temporarily disable AUTO_DETECT" into cm-10.1 5f1a9163fad53ea8184a15db07ba9b48ad288b90 Temporarily disable AUTO_DETECT 2fcce7f3be8e5400d3eb629a04dcbeda5e4bf4f8 Remove platform devices for USB functions 84a5894e45da0b88a0b79886f0300c9bfd52083e msm_msm7x2x_allocate_memory_regions() is called in MACHINE_INIT->init_early dc0f91ae8a0e87eebf1a6dfbc4d3d45a65b010e3 Fix build errors e26939a3f855c931c36706cc3f07c297ad9aedf6 Convert vreg.c consumer to regulator API 6a5156d14ebb4384cc55d1816a960eab0fc1ed23 Fix warning: value computed is not used [-Wunused-value] 07002c5c7e24725b0741969071b263dc5ddf30c7 Fix build error. Now, thunderg is building successfully. 7cb24ceb0ddb1e2e6f1a530225a8184f1e4ea836 devices-msm7x27: add missing function 'msm_add_kgsl_device' 7a4b3de2630920f03a2a9ff3e6582abc1ff6bfd9 devices-msm7x27: add msm_device_uart3 d4522b848659fec2f050c851007afeb0f6890630 pm2: add lge_set_reboot_reason for lge 4859149b53f3168f6733269c10bde8d647229b18 rpc_server_handset: add rpc_server_hs_register_callback for lge 33c9dff93fd76ba2be929ce3b1c528fd43d1a3df video: backlight: aat2870_bl: update driver to newer version ca2b40a79cff2b383b94a49916b217e57c1e1279 input: touchscreen: mcs6000: update driver to newer version a05fb11f910d529c728cc8d921e6fd77cf38d974 Cleanup P50x series defconfigs 9b6f4b2e1b6a45a2163b199eec4897b2b0e4428d video: msm: fix build error e51ed1cf485e6fed16670b14469c3a1b3adaaac7 p505 and p506 have one CPU b120c3cfff043c6c338fca7f4e9df1d95a282f98 backlight: aat2870: fixing compile errors 2b1f69b8bebaf006b3f2a8a17b460cf2f5fa1092 bcm4325: fixing compile errors eg changing MUTEX_init to init_mutex dafe26dc04eee9884f13bdf91e7489d86fc2c6da bcm4325: add missing kernel version check for include file Signed-off-by: Randolf Kastenmaier <randolf.kastenmaier@gmail.com> 46c518ad9e040b664cea7445c7e303ce7ce350f9 mmc: add missing lge stuff Signed-off-by: Randolf Kastenmaier <randolf.kastenmaier@gmail.com> aac249c071c79c7e34593a9902338f6a8ce28d16 touchscreen: mcs6000_ts: replace ioctl with unlocked_ioctl ac20da01053d57ae9c96e8d2a986cbbe10b5d49e drivers: add GPIOF stuff for mcs6000 ts driver ce46fa81c53cb63bee7497fdcbf43a09317b6033 p500 has only 1 cpu 6e297e0cf5024c8a7bb22d94233647fc631780f0 sensor: ami304: replace ioctl with unlocked_ioctl db64bb10aec476a387b0aea0aa2a4b3ef3805d77 sensor: kr3dh: replace ioctl with unlocked_ioctl 48b6afa62df78ad086cd364164b623b59c8ed4b0 sensor: kr3dm: replace ioctl with unlocked_ioctl 2071e4cb3ec52c2fbd4f4acd1b4ecfaab1e8e630 Fix more build errors 2ad1f301637e104f0b49443d66f342d7e3db89ab Fix MMC build errors c93e2b1fc5f3886b87ad516f0a1eac0f74042f86 Fix KR3DM driver build error 5295a1f1cddb3b701ed4813537994aa92460cab4 ifdef CONFIG_FB_MSM_MDP40 for borderfill 4b64e99857a9a24f6aca056ec2567b68daf6d72b thunderX: Fix build errors 2ccf69facaadd029cba499e97f7ec2bef042fa25 ifdef CONFIG_FB_MSM_MDP40 and CONFIG_FB_MSM_MDP303 ceddf74b14233fad4b1befdbbff64c677cbf326c Build clock-pcom-lookup.c for msm7x27_clock_init_data 5adec52083e6823560d268c5d36abd3cc5d790d4 MSM FB panels must be in msm ea011ea1c701f0f00eab24b3b49182aae2b7976f Revert "Modified USB driver for 6005" 39b94af12d9f906aa4d2cceaf22d02b1bf5a5c4c Don't build camera driver for now. Enable it after boot. f43ac0f85ca273349fd97244e172c78bda6b0721 Fix ISX005 camera driver build errors af6596e9abe06d2bd75ba38fc7c26f93b09dfc25 Revert "Add android vibrator device driver" e762345b5933dfd2a281e4da66187bc956d94fc1 Merge "Increase CONFIG_FRAME_WARN=2048 to fix build error" into cm-10.1 277285818c7877655f36ac5a2f286c32d88ef78d Merge "make msm7627-perf_defconfig" into cm-10.1 f67c006e89cdb94e42bb7a6170cd2a08cba1d000 Fix build error cd8e38505f cd8e38505fa990be4efb46782e282dd9e8f5947b drivers bluetooth: variable previous was moved inside lge ifdev block, but is also used outside f679d9d8dec284a38fe1ed705ab43529b0bf8585 Increase CONFIG_FRAME_WARN=2048 to fix build error 4b98a475284d327ec158ae314a0021923ba99ebb make msm7627-perf_defconfig c34a1064f72fc689320151956f9da2138ab16563 Fix multiple definition build errors e45ba725522d827885b521625fc0c41be1f7d955 Fix error: implicit declaration of function 'set_irq_wake' eca301df7e310bf60511e9e7022ce26848b76acb Update main thunderg (P50x) board file to be 3.0.31 compatible bfc18a64862042993ee2a6a6fa66690b01be5ce7 Merge "Edit bluetooth driver to support P50x bluetooth" into cm-10.1 fde6ba34fee297dbcb690f7acaa1c18602fe717c Edit bluetooth driver to support P50x bluetooth 8f8f26bd8eee7c1b98481a868224b8b5fe023020 Merge "Upgrade Hitachi and Novatek display systems" into cm-10.1 3897cfc221bd25d04a0d236863859124cde5e48f Upgrade Hitachi and Novatek display systems 8d288a1df9a5fa7eee71eca47607afd346423068 Merge "Update camera driver" into cm-10.1 ffdb929efe6bdbf8b89258cfbdbe3176e5dd315b Merge "Backlit driver fix" into cm-10.1 4855ce9fa944ac0433c6e0d2957448358782395a Update camera driver db4ea240d176bab2ff8c65dd32a324d3c3010131 Merge "[P350] Pecan board file fixes" into cm-10.1 0edfe50a98bd6f2ffbad17cd8ab1656aba84bec3 Merge "devices_lge.c: include <linux/bootmem.h>" into cm-10.1 7cb34351eddf7c98a4002597ae6c7e5ffc04e570 [P350] Pecan board file fixes 9cf646cefd34b9cc663fd64b79488c27b1e6325d Backlit driver fix 820550cf799433845511e1fd2e141cdc2c18b180 devices_lge.c: include <linux/bootmem.h> d283a2942b48043456c6ee0ca584d532e8b7662d ignore compile error in snd_pcm_client.c:192:19: warning: operation on 'audio->out_tail' may be undefined [-Wsequence-point] b3288d19bf6adb4b79ff1821177e22fe83deff4b Update ThunderG (P50X) board files to 2.6.38 compatible a3b192866385c3eff9e641ed440ebb320a2c4e92 Merge "change in board-thunderg-input.c: tv.nsec to tv_nsec" into cm-10.1 24a44712c22826647f2abff63ef3badbce3f023e Merge "add rpc_server_hs_register_callback for lge" into cm-10.1 a4681591dbdab725ae003645f07c8606d5e11c61 Fix build error for b462f1467b 5a576a32327107b49ed7468b4c143474bfba2abc change in board-thunderg-input.c: tv.nsec to tv_nsec 37fa4d4420d4571a35ee4a1137161e8bd9112fbd add rpc_server_hs_register_callback for lge 756bd8c353f439391327c7b759a517bb1e2e2edd Merge "net: fix bcm4325 could not be selected" into cm-10.1 fabe456a183c6bac993b1f0c1e7f987957a176eb Merge "Remove Jump board files" into cm-10.1 a812661f9d8e75d204c69092a998b0b7b03058b0 net: fix bcm4325 could not be selected 4acb11c4ef68cc01ab8300de25376ec9695a7937 Add LGE_REV_G revision for only pecan fc2af6f2e3e8ddbdb528d9643cb9acf7907eaf78 Revert "remove LGE_REV_G from board_lge.h" db09e93bb723c0550a5847ca20d3b12925f4ede6 remove LGE_REV_G from board_lge.h 4c611466e4f692af105d1f8fa55fba0de790ec4a Merge "[P350] Add missing pecan define" into cm-10.1 aaad2e6d3f59bb93578b77067d048a6f0a60b27b Force SUBARCH := arm 53efb0475901584933f47fa51e2d70d5cefb8786 fix compile error on qdsp5: unused variables removed (-Wunused-variable) b462f1467b7a92bce244cc4a9dbb429049dde238 [P350] Add missing pecan define 9761286737a01fdda9cd11f52776cc91a64221e0 [P350] reduce msm_fb and pmem_mdp size for pecan 44e8106c4881a42a876679407fce7cac44bac152 Remove Jump board files 8455993445bfc2ee7af3e7d54d5bcb5bd68abff8 [P350][C660] cleanup mcs7000_ts ee219a140f99d411181764bb3449b47c74a3c308 [P350] replace .ioctl with .unlocked_ioctl 882c0c6e24e47b7923c7edbb6df3121655b0f26a Add missing sensor header file ed35c1c42e3c75c77fa432c4f8ed17623913a594 Add SHARP/Novatek LCD Driver 587595873dc722b71d9f8cd151761bc7f161da7a Merge "update p350 board files to 3.0" into cm-10.1 1ae6d39ee35e365b44ac3fc156d6852d73c3432f I'm sure I'd already updated this file to it's 3.0 version fe38da9edc46510b807a267d3bba5656f3c96b16 fix lge make file ffc218933c4dd8d4168956492c453047f9061c50 fix up sensors make file 3b24468c9b06874f362e0207f4fa14082dfbb008 Merge "Add missing endif" into cm-10.1 a2e52bd9068be62ba7d421fcb5b43daaad062074 Add missing endif de6184882525c25a50cc90b87b442d43b069d706 Merge "common: add missing board files for LG devices" into cm-10.1 155ba8d7c73018d5e2fb177bc0eed7dc86facf34 update p350 board files to 3.0 20015b605d704e4d8d03c1b189b04d4b9b075088 Merge "Add BCM4330 driver from 2.6" into cm-10.1 efeb829dbce32a04ede526b91dd6221aca6fed1b Merge "Use old 2.6 BCM4329 driver" into cm-10.1 39ece3e322aee94f79e04520f4df78ef80633deb common: add missing board files for LG devices d1e9819faa4507ab731aea47c52d63133215d58c [COMMON] increase max nand partition b93efeb411fc6f102129a86dd617a2cfd45d88e9 Add sensor for pecan 0d09f01409dad67cfea29b0b5e41c46679c6cd92 fix error: unterminated #ifndef 2ba29644053a830072b73f1ce317026bf18441bb Merge "bump p350 board files to version .38 for reference for a later use" into cm-10.1 df9dea8b3e574c42eaf74ebd6d4efdd09d27c380 Merge "Add lge devices in Kconfig , Makefile.boot" into cm-10.1 fdfb9ade380fc68e7a13b151c488540191f9d41d Merge "common: Add sensors drivers" into cm-10.1 09412e63a8e9608531258ef0d38459b72e4e934c Add lge devices in Kconfig , Makefile.boot 241ecbc3e6cf69b5a3850276ac610bc608decf78 bump p350 board files to version .38 for reference for a later use 1a253335999d713aa2675f51df4bb1fed05ef629 Add pecan in lge_temp file d7d70013ad0a3f7a3f95cb420cec90c737ee7e18 Add mcs700 touchscreen driver for muscat and pecan 6ea08683bc7d3ff052135d4475cb45c72b82510c [P350] Fix override warnings 2ad9fe5df8891ffbcafc53958f1c2ad29cf66fa9 Add BCM4330 driver from 2.6 10491abbbc5b3408910c2629219c7dc00b771f9d Use old 2.6 BCM4329 driver 6822f71c98acf7bc88a29bc1aa27440ff2a45e82 Remove BCM4325-new driver, use old one instead f681c699123185e50024d716f84b94ee9804543b Add missing functions 56a94e0798c8774673bb84db68097128c4913a34 Merge "Add old BCM4325 driver, Wi-Fi fixes, and start new BCM4325 driver" into cm-10.1 ca003bc6a01d6d2593ee782e261edba287c528c4 Add old BCM4325 driver, Wi-Fi fixes, and start new BCM4325 driver 1942fa4367de723c141107d6f66a7241250e4118 Merge "Add old BCM4325 driver, Wi-Fi fixes, and start new BCM4325 driver" into cm-10.1 745cd1f1391c31b74095df15d6e061f1f307f4e2 bump p50x series to 3.0 defconfigs c95bbb30ace3f238d9c002a7ba198291cc81d2d9 common: Add sensors drivers ff20e1b1ad28d17e2efe541522fcc13adbeacdcc and the headers 9ee31309b6dcf03cc5e86fa605e3419e506116a5 add lge folder to mach-msm add p350 .35 board files, ready for updating to 3.0 lge folder is 3.0 b36527fef8b2760c1a3737fb9fc764ba22077a7f p350 defconfig the full history can be found here https://github.com/PecanCM/p350-caf-3.x/commits/3.0/arch/arm/configs/cyanogenmod_pecan_defconfig e05461cdc060e3b064780c4964074db551075c1d Add old BCM4325 driver, Wi-Fi fixes, and start new BCM4325 driver 99a2cc9e086702c9d034ef2806af9735b35b361a Add battery device drivers 08ba21248a505bbeea070cd87bb0d6b27dd5a35a Modified USB driver for 6005 111f224fc030da4f22190897fc6e8fa68921f435 Add LGE_DIAGTEST b0754b5ee684ec5e6e9e7dbce773c6aee1b77df0 Modify control definition of msm_audio 6b039cbe38c86b9fe672a5231230ee6e36f3c522 Modify sound path cf1d7b7d0f853c7424d3d2d4ca18f0d5df226ce8 Add android vibrator device driver f32c85da5fd14a8d80b44b3204e6654c963aafb4 Fix IRQ error 96974362036c592908dda44f2f244e3d7092a3f4 Add isx005 camera device driver bc16da8bd7b37339ad1d422e0e01b0cbe30bdb15 Add a few LG things to the Makefile efd939f13ffd0cf886e5a69069bd7f8f571f6cc7 Enable touchscreen debug logging 3edccebb3bee716c81bf97304fd0015018eb64e1 Modify memory address for 4Gb DDR 6e7c65ab1981702879a60e10e1f1a27d94639c8b Add mcs6000 touchscreen device driver 1384c95768be2a7b0f4871e40c3b55a8e379cbdf Add workaround code to fix mdp bug 643a1ae6a66fcf289a45964760a5d819e27a6bee Merge "LCD: add the ebi2_tovis LCD Pannel for QVGA devices" into cm-10.1 0c27c6ff5a2076b87cd3f43910e2ee7325e8eec3 LCD: add the ebi2_tovis LCD Pannel for QVGA devices 84a2ccda0843fec8b2e629ea4420ae03df119359 Little things for virator and surfing 9f200ab14e877358f7ae4b6447d37215626600e7 Add lcd driver. - hitachi hvga 41301fb5d417cfc40d87610768640904dfcc7d2d Add the backlight device driver 62582095b6ef8f35ebb24d73d44939e89f41af1d Add MSM_WEB register 1ae41325fee34b92de173637207bc0d32147fa02 Modify structure for msm camera f34d123630a4426ab8b9b3c97d60ee19564880e8 Initial LGE Configs
Conflicts:
	arch/arm/mach-msm/smd.c
	drivers/mmc/host/msm_sdcc.c